# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0007_auto_20160821_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deckcard',
            name='board',
            field=models.CharField(choices=[('main', 'main'), ('side', 'side'), ('command', 'command')], default='main', max_length=8),
        ),
    ]
