# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='contentblock',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('live', 'live'), ('inactive', 'inactive')], default='draft', max_length=12),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='key',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='contentblock',
            unique_together=set([('key', 'version')]),
        ),
    ]
