# Generated by Django 2.1.9 on 2019-06-11 22:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardprice',
            name='at_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
