# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-21 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_format_abbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basecard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='basecard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='battle_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cardrating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunSQL("UPDATE type SET sort_order = 1000"),
        migrations.RunSQL("UPDATE type SET sort_order = 0 WHERE type = 'Creature'"),
        migrations.RunSQL("UPDATE type SET sort_order = 1 WHERE type = 'Artifact'"),
        migrations.RunSQL("UPDATE type SET sort_order = 2 WHERE type = 'Enchantment'"),
        migrations.RunSQL("UPDATE type SET sort_order = 3 WHERE type = 'Instant'"),
        migrations.RunSQL("UPDATE type SET sort_order = 4 WHERE type = 'Sorcery'"),
        migrations.RunSQL("UPDATE type SET sort_order = 5 WHERE type = 'Land'"),
        migrations.RunSQL("UPDATE type SET sort_order = 6 WHERE type = 'Planeswalker'"),
    ]
