# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-06 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20160821_0523'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSupertype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('basecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.BaseCard')),
            ],
            options={
                'db_table': 'cardsupertype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Supertype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supertype', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'supertype',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='cardsupertype',
            name='supertype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Supertype'),
        ),
        migrations.AddField(
            model_name='basecard',
            name='supertypes',
            field=models.ManyToManyField(through='cards.CardSupertype', to='cards.Supertype'),
        ),
        migrations.AlterUniqueTogether(
            name='cardsupertype',
            unique_together=set([('basecard', 'position')]),
        ),
    ]
