# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-07 02:21
from __future__ import unicode_literals

from django.db import migrations

def add_color(apps, schema_editor):
    colors = {'w':"White",
              'u':"Blue",
              'b':"Black",
              'r':"Red",
              'g':"Green",
              'c':"Colorless"}
        
    Color = apps.get_model('cards', 'Color')
    
    for color_id in colors:
        try:
            color_obj = Color.objects.get(id=color_id)
        except Color.DoesNotExist:
            color_obj = Color.objects.create(id=color_id)
            color_obj.color = colors[color_id]
            color_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20171106_2220'),
    ]

    operations = [
        migrations.RunPython(add_color),
    ]
