# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_basecard_ispermanent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatBannedCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Format')),
                ('physicalcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.PhysicalCard')),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'Format Banned Cards',
            },
        ),
        migrations.CreateModel(
            name='FormatExpansionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expansionset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.ExpansionSet')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Format')),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'Format Expansion Sets',
            },
        ),
    ]
