# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_auto_20171116_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='bannedcards',
            field=models.ManyToManyField(through='cards.FormatBannedCard', to='cards.PhysicalCard'),
        ),
    ]
