# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_auto_20171205_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='test',
        ),
        migrations.AlterField(
            model_name='battle',
            name='loser_pcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_battles', to='cards.PhysicalCard'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='winner_pcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_battles', to='cards.PhysicalCard'),
        ),
        migrations.AlterUniqueTogether(
            name='cardrating',
            unique_together=set([('physicalcard', 'format')]),
        ),
        migrations.RemoveField(
            model_name='cardrating',
            name='test',
        ),
        migrations.DeleteModel(
            name='BattleTest',
        ),
    ]
