# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_auto_20180109_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_datetime', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField(default=0.0)),
                ('price_discounted', models.BooleanField(default=False)),
                ('printing', models.CharField(max_length=25)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Card')),
            ],
            options={
                'db_table': 'cardprice',
                'managed': True,
            },
        ),
    ]
